[project]
name = "plan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mysql-connector-python>=9.3.0",
    "Flask>=3.0.0",
    "Flask-CORS>=4.0.0",
]